project_id = "bpdtjjhexygryvxrhivl"

[auth]
site_url = "https://nudofy.app"
additional_redirect_urls = ["nudofy://**"]

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email.template.recovery]
subject = "Restablece tu contraseña - Nudofy"
content_path = "./supabase/templates/recovery.html"
